#!/bin/bash
#PBS -l nodes=1:ppn=2,walltime=3:00:00
#PBS -N app-mrtrix3-5tt

# generate 5tt
time singularity exec -e docker://brainlife/mrtrix3:3.0.3 ./5tt.sh

# convert gm, wm, csf masks
time singularity exec -e docker://brainlife/3.0_RC3 ./binarize.sh
